name: Docker Image CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
jobs:
  build:
    name: Build a Docker container
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - name: Set tag name
      id: tag
      run: echo "::set-output name=tag::$(date +%s)"
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chamithlkml/php-cmd-line-operator:${{ steps.tag.outputs.tag }}

    - name: Push docker image to hub
      run: docker push chamithlkml/php-cmd-line-operator:${{ steps.tag.outputs.tag }}
