name: Docker Image CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
jobs:
  build:
    name: Build a Docker container
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: cd ../../../ && docker build . --file ./Dockerfile --tag chamithlkml/php-cmd-line-operator:$(date +%s)
